package pdf

import (
	"fmt"

	"github.com/jung-kurt/gofpdf"
	"github.com/kartik-Gehlot/RedRecon/internal/ai"
	"github.com/kartik-Gehlot/RedRecon/internal/models"
)

func Generate(scan *models.Scan, analysis ai.Analysis) error {

	pdf := gofpdf.New("P", "mm", "A4", "")

	pdf.SetTitle("RedRecon Security Report", false)

	pdf.AddPage()

	// ---------- Title ----------

	pdf.SetFillColor(183, 28, 28)
	pdf.Rect(0, 0, 210, 30, "F")

	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Arial", "B", 22)

	pdf.SetXY(15, 10)
	pdf.Cell(0, 10, "RedRecon Security Report")

	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(25)

	pdf.Ln(15)

	pdf.SetFont("Arial", "", 12)

	pdf.Cell(45, 8, "Target:")
	pdf.Cell(100, 8, scan.Target)

	pdf.Ln(8)

	pdf.Cell(45, 8, "Version:")
	pdf.Cell(100, 8, scan.Version)

	pdf.Ln(8)

	pdf.Cell(45, 8, "Status:")
	pdf.Cell(100, 8, scan.Status)

	pdf.Ln(15)

	// ---------- Executive Summary ----------

	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(190, 10, "Executive Summary")

	pdf.Ln(10)

	pdf.SetFont("Arial", "", 12)

	pdf.MultiCell(
		190,
		7,
		analysis.ExecutiveSummary,
		"",
		"L",
		false,
	)

	pdf.Ln(5)

	// ---------- Risk ----------

	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(190, 10, "Overall Risk")

	pdf.Ln(10)

	pdf.SetFont("Arial", "B", 13)

	switch analysis.Risk {
	case "Critical":
		pdf.SetFillColor(183, 28, 28)
	case "High":
		pdf.SetFillColor(239, 68, 68)
	case "Medium":
		pdf.SetFillColor(245, 158, 11)
	default:
		pdf.SetFillColor(34, 197, 94)
	}

	pdf.SetTextColor(255, 255, 255)

	pdf.CellFormat(
		40,
		10,
		analysis.Risk,
		"",
		0,
		"C",
		true,
		0,
		"",
	)

	pdf.SetTextColor(0, 0, 0)

	pdf.Ln(15)

	pdf.Ln(12)

	// ---------- Top Risks ----------

	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(190, 10, "Top Risks")

	pdf.Ln(10)

	pdf.SetFont("Arial", "", 12)

	for _, risk := range analysis.TopRisks {

		pdf.Cell(5, 8, "-")

		pdf.Cell(180, 8, risk)

		pdf.Ln(8)

	}

	pdf.Ln(5)
	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(190, 10, "Statistics")

	pdf.Ln(10)

	pdf.SetFont("Arial", "", 12)

	alive := 0
	ports := 0
	secrets := 0
	findings := 0

	for _, host := range scan.Hosts {

		if host.Alive {
			alive++
		}

		ports += len(host.Ports)
		secrets += len(host.Secrets)
		findings += len(host.Findings)
	}

	pdf.SetFillColor(245, 245, 245)

	y := pdf.GetY()

	pdf.Rect(15, y, 180, 35, "F")

	pdf.SetXY(20, y+6)

	pdf.SetFont("Arial", "B", 13)

	pdf.Cell(80, 8, fmt.Sprintf("Hosts : %d", len(scan.Hosts)))
	pdf.Cell(80, 8, fmt.Sprintf("Alive : %d", alive))

	pdf.Ln(10)

	pdf.SetX(20)

	pdf.Cell(80, 8, fmt.Sprintf("Ports : %d", ports))
	pdf.Cell(80, 8, fmt.Sprintf("Secrets : %d", secrets))

	pdf.Ln(10)

	pdf.SetX(20)

	pdf.Cell(80, 8, fmt.Sprintf("Findings : %d", findings))

	pdf.Ln(20)
	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(190, 10, "Discovered Hosts")

	pdf.Ln(10)

	pdf.SetFillColor(230, 230, 230)

	pdf.SetFont("Arial", "B", 11)

	pdf.CellFormat(
		90,
		8,
		"Hostname",
		"1",
		0,
		"L",
		true,
		0,
		"",
	)

	pdf.CellFormat(
		30,
		8,
		"Status",
		"1",
		0,
		"C",
		true,
		0,
		"",
	)

	pdf.CellFormat(
		30,
		8,
		"HTTP",
		"1",
		1,
		"C",
		true,
		0,
		"",
	)

	pdf.SetFont("Arial", "", 10)

	limit := 20

	for i, host := range scan.Hosts {

		if i >= limit {
			break
		}

		status := "Dead"

		if host.Alive {
			status = "Alive"
		}

		pdf.CellFormat(
			90,
			7,
			host.Hostname,
			"1",
			0,
			"L",
			false,
			0,
			"",
		)

		pdf.CellFormat(
			30,
			7,
			status,
			"1",
			0,
			"C",
			false,
			0,
			"",
		)

		pdf.CellFormat(
			30,
			7,
			fmt.Sprintf("%d", host.StatusCode),
			"1",
			1,
			"C",
			false,
			0,
			"",
		)
	}
	if len(scan.GithubFindings) > 0 {

		pdf.SetFont("Arial", "B", 16)
		pdf.Cell(190, 10, "GitHub Findings")
		pdf.Ln(10)

		pdf.SetFont("Arial", "", 11)

		for _, finding := range scan.GithubFindings {

			pdf.MultiCell(
				190,
				6,
				fmt.Sprintf(
					"Repository: %s\nFile: %s\nURL: %s",
					finding.Repository,
					finding.File,
					finding.URL,
				),
				"",
				"L",
				false,
			)

			pdf.Ln(2)
		}
	}
	// ---------- Recommendations ----------

	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(190, 10, "Recommendations")

	pdf.Ln(10)

	pdf.SetFont("Arial", "", 12)

	for _, rec := range analysis.Recommendations {

		pdf.Cell(5, 8, "-")

		pdf.Cell(180, 8, rec)

		pdf.Ln(8)

	}
	pdf.SetY(-15)

	pdf.SetFont("Arial", "I", 9)

	pdf.CellFormat(
		0,
		10,
		"Generated by RedRecon v1.0 | Developed by Kartik Gehlot",
		"",
		0,
		"C",
		false,
		0,
		"",
	)
	pdf.SetFooterFunc(func() {

		pdf.SetY(-12)

		pdf.SetFont("Arial", "I", 9)

		pdf.CellFormat(
			0,
			10,
			fmt.Sprintf(
				"Page %d",
				pdf.PageNo(),
			),
			"",
			0,
			"C",
			false,
			0,
			"",
		)

	})
	return pdf.OutputFileAndClose("output/report.pdf")
}
